/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ComposeForm: typeof import('./src/components/ComposeForm.vue')['default']
    ComposeHeader: typeof import('./src/components/ComposeHeader.vue')['default']
    ComposeScreen: typeof import('./src/components/ComposeScreen.vue')['default']
    FeedEntry: typeof import('./src/components/FeedEntry.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PromptCopySourceDialog: typeof import('./src/components/PromptCopySourceDialog.vue')['default']
    RedirectSourceDialog: typeof import('./src/components/RedirectSourceDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceCard: typeof import('./src/components/SourceCard.vue')['default']
  }
}
